[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "contracts/=src/",
]

[fuzz]
runs = 1024

[invariant]
runs = 256
depth = 64
fail_on_revert = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
